import { SiteContent } from '@/types';

export const nlContent: SiteContent = {
  locale: 'nl',
  meta: {
    title: 'Drake - Framer Designer & Ontwikkelaar',
    description: 'Ik ontwerp en codeer prachtig eenvoudige dingen en ik hou van wat ik doe. Zo simpel is het!',
  },
  profile: {
    name: 'Drake',
    title: 'Framer Designer',
    subtitle: '& Ontwikkelaar',
    email: 'hello@drake.design',
    location: 'Gevestigd in Los Angeles, CA',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
    copyright: '© 2024 Drake. Alle rechten voorbehouden',
    hireButtonText: 'NEEM CONTACT OP!',
    socialLinks: [
      { platform: 'twitter', url: 'https://twitter.com', label: 'Twitter' },
      { platform: 'dribbble', url: 'https://dribbble.com', label: 'Dribbble' },
      { platform: 'instagram', url: 'https://instagram.com', label: 'Instagram' },
      { platform: 'github', url: 'https://github.com', label: 'GitHub' },
    ],
  },
  hero: {
    sectionLabel: 'INTRODUCTIE',
    greeting: 'Hallo van',
    name: 'Drake',
    title: 'Framer Designer en Ontwikkelaar',
    description: 'Ik ontwerp en codeer prachtig eenvoudige dingen en ik hou van wat ik doe. Zo simpel is het!',
    scrollCta: 'MIJN PROJECTEN',
  },
  about: {
    sectionLabel: 'OVER MIJ',
    heading: 'Elk geweldig ontwerp begint met een nog',
    headingAccent: 'beter verhaal',
    paragraphs: [
      'Sinds ik bijna 8 jaar geleden mijn reis als freelance designer begon, heb ik op afstand gewerkt voor bureaus, startups geadviseerd en samengewerkt met getalenteerde mensen om digitale producten te maken voor zowel zakelijk als consumentengebruik.',
      'Ik ben rustig zelfverzekerd, van nature nieuwsgierig en werk voortdurend aan het verbeteren van mijn vaardigheden - één ontwerpprobleem tegelijk.',
    ],
  },
  resume: {
    sectionLabel: 'CV',
    heading: 'Opleiding &',
    headingAccent: 'Ervaring',
    educationTitle: 'Opleiding',
    experienceTitle: 'Ervaring',
    education: [
      {
        id: 'edu-1',
        period: '2018 - 2022',
        title: 'Bachelor in Design',
        organization: 'California Institute of Arts',
        description: 'Focus op UI/UX-ontwerp en interactieve media',
      },
      {
        id: 'edu-2',
        period: '2016 - 2018',
        title: 'Associate Degree in Webontwikkeling',
        organization: 'Los Angeles Community College',
      },
    ],
    experience: [
      {
        id: 'exp-1',
        period: '2022 - Heden',
        title: 'Senior Framer Ontwikkelaar',
        organization: 'Freelance',
        description: 'Bouwen van hoogwaardige websites en applicaties met Framer, Webflow en React',
      },
      {
        id: 'exp-2',
        period: '2020 - 2022',
        title: 'UI/UX Designer',
        organization: 'Creative Agency Co.',
        description: 'Leidde ontwerp voor 20+ klantprojecten',
      },
      {
        id: 'exp-3',
        period: '2018 - 2020',
        title: 'Junior Webontwikkelaar',
        organization: 'TechStart Inc.',
      },
    ],
  },
  services: {
    sectionLabel: 'DIENSTEN',
    heading: 'Mijn',
    headingAccent: 'Specialisaties',
    services: [
      {
        id: 'svc-1',
        title: 'Website Ontwerp',
        description: 'Ik creëer digitale producten met unieke ideeën met Figma & Framer',
        projectCount: 24,
        projectLabel: 'PROJECTEN',
        icon: 'design',
      },
      {
        id: 'svc-2',
        title: 'Ontwikkeling',
        description: 'Ik bouw websites live met Framer, Webflow of WordPress',
        projectCount: 126,
        projectLabel: 'PROJECTEN',
        icon: 'code',
      },
      {
        id: 'svc-3',
        title: 'SEO/Marketing',
        description: 'Verhoog het verkeer naar uw website met SEO-optimalisatie',
        projectCount: 8,
        projectLabel: 'PROJECTEN',
        icon: 'seo',
      },
    ],
  },
  skills: {
    sectionLabel: 'MIJN VAARDIGHEDEN',
    heading: 'Mijn',
    headingAccent: 'Voordelen',
    skills: [
      { id: 'skill-1', name: 'Figma', percentage: 92, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg' },
      { id: 'skill-2', name: 'Framer', percentage: 85, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/framermotion/framermotion-original.svg' },
      { id: 'skill-3', name: 'Webflow', percentage: 80, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/webflow/webflow-original.svg' },
      { id: 'skill-4', name: 'React', percentage: 90, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
      { id: 'skill-5', name: 'WordPress', percentage: 86, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/wordpress/wordpress-plain.svg' },
      { id: 'skill-6', name: 'Laravel/PHP', percentage: 70, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/laravel/laravel-original.svg' },
    ],
  },
  portfolio: {
    sectionLabel: 'PORTFOLIO',
    heading: 'Uitgelichte',
    headingAccent: 'Projecten',
    projects: [
      {
        id: 'proj-1',
        title: 'Bureau - Architectuurstudio Website',
        category: 'Webontwerp',
        imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop',
        tags: ['Figma', 'Framer', 'WordPress'],
        link: '#',
      },
      {
        id: 'proj-2',
        title: 'Hinterland - Vastgoed Site Herontwerp',
        category: 'Webontwerp',
        imageUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop',
        tags: ['Figma', 'React'],
        link: '#',
      },
      {
        id: 'proj-3',
        title: 'Lewis Studio - Creatief Bureau',
        category: 'Branding',
        imageUrl: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=800&h=600&fit=crop',
        tags: ['Framer'],
        link: '#',
      },
      {
        id: 'proj-4',
        title: 'Serenity - Gezondheid & Wellness App',
        category: 'Mobiele App',
        imageUrl: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&h=600&fit=crop',
        tags: ['Figma', 'React Native'],
        link: '#',
      },
    ],
  },
  testimonials: {
    sectionLabel: 'GETUIGENISSEN',
    heading: 'Vertrouwd door',
    headingAccent: 'honderden klanten',
    testimonials: [
      {
        id: 'test-1',
        quote: 'Drake - Een ontwikkelaar met creativiteit, professionaliteit en meesterschap in code. Veel meer dan verwacht. Hoogwaardige producten & flexibele prijzen. Aanbevolen!',
        authorName: 'Paublo Dybala',
        authorTitle: 'CEO',
        authorCompany: 'IBM Global',
        authorImageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
        projectLink: '#',
        projectLabel: 'PROJECT',
      },
      {
        id: 'test-2',
        quote: 'Uitzonderlijke werkkwaliteit en geweldige communicatie gedurende het hele project. Zou zeker weer met Drake werken!',
        authorName: 'Sarah Johnson',
        authorTitle: 'Oprichter',
        authorCompany: 'StartupXYZ',
        authorImageUrl: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face',
        projectLink: '#',
        projectLabel: 'PROJECT',
      },
      {
        id: 'test-3',
        quote: 'De aandacht voor detail en het ontwerpgevoel zijn uitstekend. Drake heeft onze visie omgezet in werkelijkheid.',
        authorName: 'Michael Chen',
        authorTitle: 'Productmanager',
        authorCompany: 'TechCorp',
        authorImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
        projectLink: '#',
        projectLabel: 'PROJECT',
      },
    ],
  },
  clients: {
    heading: 'SAMENWERKING MET 60+ MERKEN WERELDWIJD',
    clients: [
      { id: 'client-1', name: 'BLB', logoUrl: 'https://via.placeholder.com/150x50?text=BLB' },
      { id: 'client-2', name: 'Christopher Willis', logoUrl: 'https://via.placeholder.com/150x50?text=CW' },
      { id: 'client-3', name: 'Serenity Hotel', logoUrl: 'https://via.placeholder.com/150x50?text=Serenity' },
      { id: 'client-4', name: 'Artchive', logoUrl: 'https://via.placeholder.com/150x50?text=Artchive' },
      { id: 'client-5', name: 'Neuton Interactive', logoUrl: 'https://via.placeholder.com/150x50?text=Neuton' },
      { id: 'client-6', name: 'Papillon', logoUrl: 'https://via.placeholder.com/150x50?text=Papillon' },
      { id: 'client-7', name: 'Good Habits', logoUrl: 'https://via.placeholder.com/150x50?text=GoodHabits' },
      { id: 'client-8', name: 'Creative Space', logoUrl: 'https://via.placeholder.com/150x50?text=Creative' },
    ],
  },
  contact: {
    sectionLabel: 'CONTACT',
    heading: 'Laten we',
    headingAccent: 'samenwerken!',
    email: 'hello@drake.design',
    fields: [
      { id: 'name', label: 'VOLLEDIGE NAAM', placeholder: 'Uw volledige naam', type: 'text', required: true },
      { id: 'email', label: 'E-MAIL', placeholder: 'Uw e-mailadres', type: 'email', required: true },
      { id: 'phone', label: 'TELEFOON (optioneel)', placeholder: 'Uw telefoonnummer', type: 'tel', required: false },
      { id: 'subject', label: 'ONDERWERP', placeholder: 'Selecteer een onderwerp', type: 'select', required: true, options: ['Website Ontwerp', 'Ontwikkeling', 'SEO/Marketing', 'Anders'] },
      { id: 'budget', label: 'UW BUDGET (optioneel)', placeholder: 'Een budgetbereik voor uw project', type: 'text', required: false },
      { id: 'message', label: 'BERICHT', placeholder: 'Schrijf uw bericht hier ...', type: 'textarea', required: true },
    ],
    attachmentLabel: 'BIJLAGE TOEVOEGEN',
    submitButtonText: 'BERICHT VERZENDEN',
  },
  navigation: {
    items: [
      { id: 'nav-1', label: 'Home', icon: 'home', sectionId: 'hero' },
      { id: 'nav-2', label: 'Over mij', icon: 'about', sectionId: 'about' },
      { id: 'nav-3', label: 'CV', icon: 'resume', sectionId: 'resume' },
      { id: 'nav-4', label: 'Diensten', icon: 'services', sectionId: 'services' },
      { id: 'nav-5', label: 'Vaardigheden', icon: 'skills', sectionId: 'skills' },
      { id: 'nav-6', label: 'Portfolio', icon: 'portfolio', sectionId: 'portfolio' },
      { id: 'nav-7', label: 'Getuigenissen', icon: 'testimonials', sectionId: 'testimonials' },
      { id: 'nav-8', label: 'Contact', icon: 'contact', sectionId: 'contact' },
    ],
  },
  theme: {
    toggleTheme: 'Thema wisselen',
    lightMode: 'Naar lichte modus',
    darkMode: 'Naar donkere modus',
  },
};
